Pinpoint.Plugin.Spotify/AuthenticationManager.cs
Pinpoint.Plugin.Spotify/LocalServer.cs

Display Spotify confirmation msg that authentication succeeded

---

Pinpoint.Core/AppSettings.cs
Pinpoint.Core/PluginEngine.cs
Pinpoint.Plugin.AppSearch/AppSearchFrequency.cs
Pinpoint.Plugin.Snippets/SnippetsPlugin.cs
Pinpoint.Plugin.Spotify/Client/SpotifyClient.cs
Pinpoint.Plugin.Spotify/SpotifyPlugin.cs
Pinpoint.Win/Models/MainWindowModel.cs
Pinpoint.Win/Models/SettingsWindowModel.cs

Refactor `AppSettings` to be consistent

---

Pinpoint.Core/PluginEngine.cs
Pinpoint.Plugin.Notes/AddNoteResult.cs
Pinpoint.Plugin.Notes/DeleteNoteOptionResult.cs
Pinpoint.Plugin.Notes/Note.cs
Pinpoint.Plugin.Notes/NoteResult.cs
Pinpoint.Plugin.Notes/NotesFile.cs
Pinpoint.Plugin.Notes/NotesManager.cs
Pinpoint.Plugin.Notes/NotesPlugin.cs
Pinpoint.Plugin.Notes/Pinpoint.Plugin.Notes.csproj
Pinpoint.Win/Pinpoint.Win.csproj
Pinpoint.Win/View/MainWindow.xaml.cs
Pinpoint.sln
README.md

List notes by typing a query starting with "notes".
Get "add notes" result by typing "notes+" or "notes-add".
Delete notes by selecting the "delete note" alt-option.

Implement quick note plugin

---

Pinpoint.Plugin.ColorConverter/ColorConversionResult.cs
Pinpoint.Plugin.ColorConverter/ColorConverterPlugin.cs
Pinpoint.Plugin.ColorConverter/Pinpoint.Plugin.ColorConverter.csproj
Pinpoint.Win/Pinpoint.Win.csproj
Pinpoint.Win/View/MainWindow.xaml.cs
Pinpoint.sln

Convert from hex -> rgb and rgb -> hex. Closes #20.

Color converter plugin

---

Pinpoint.Plugin.Bookmarks/BookmarksPlugin.cs
Pinpoint.Plugin.Bookmarks/BraveBookmarkExtractor.cs
Pinpoint.Plugin.Bookmarks/BraveBookmarkFileLocator.cs
Pinpoint.Plugin.Bookmarks/BrowserType.cs
Pinpoint.Plugin.Bookmarks/DefaultBookmarkResult.cs
Pinpoint.Plugin.Bookmarks/FirefoxBookmarkExtractor.cs
README.md

Add brave bookmarks. No need to locate default browser, just get all

---

Pinpoint.Plugin.PasswordGenerator/PasswordErrorResult.cs
Pinpoint.Plugin.PasswordGenerator/PasswordGeneratorPlugin.cs
Pinpoint.Plugin.PasswordGenerator/PasswordResult.cs
Pinpoint.Plugin.PasswordGenerator/Pinpoint.Plugin.PasswordGenerator.csproj
Pinpoint.Win/Pinpoint.Win.csproj
Pinpoint.Win/View/MainWindow.xaml.cs
Pinpoint.sln

Variable length password generator plugin

---

Pinpoint.Core/AppConstants.cs
Pinpoint.Core/PluginEngine.cs
Pinpoint.Core/Results/AbstractQueryResult.cs
Pinpoint.Plugin.Bookmarks/Pinpoint.Plugin.Bookmarks.csproj
Pinpoint.Plugin.ClipboardManager/ClipboardHistory.cs
Pinpoint.Plugin.ClipboardManager/ClipboardManagerPlugin.cs
Pinpoint.Plugin.ClipboardManager/ClipboardResult.cs
Pinpoint.Plugin.ClipboardManager/IClipboardEntry.cs
Pinpoint.Plugin.ClipboardManager/ImageClipboardEntry.cs
Pinpoint.Plugin.ClipboardManager/Pinpoint.Plugin.ClipboardManager.csproj
Pinpoint.Plugin.ClipboardManager/TextClipboardEntry.cs
Pinpoint.Win/Models/SettingsWindowModel.cs
Pinpoint.Win/Pinpoint.Win.csproj
Pinpoint.Win/View/MainWindow.xaml.cs
Pinpoint.Win/View/SettingsWindow.xaml
Pinpoint.Win/View/SettingsWindow.xaml.cs
Pinpoint.sln

Clipboard manager plugin

---

Pinpoint.Plugin.Weather/Models/ConditionModel.cs
Pinpoint.Plugin.Weather/Models/WeatherDayModel.cs
Pinpoint.Plugin.Weather/Models/WeatherHourModel.cs
Pinpoint.Plugin.Weather/Pinpoint.Plugin.Weather.csproj
Pinpoint.Plugin.Weather/WeatherIconRepository.cs
Pinpoint.Plugin.Weather/WeatherPlugin.cs
Pinpoint.Plugin.Weather/WeatherResult.cs
Pinpoint.Win/Pinpoint.Win.csproj
Pinpoint.Win/View/MainWindow.xaml.cs
Pinpoint.Win/View/SettingsWindow.xaml
Pinpoint.sln

Implement weather forecast plugin

---

Pinpoint.Core/Pinpoint.Core.csproj
Pinpoint.Win/View/MainWindow.xaml.cs

The program exited with an error because the Selected index is changed when TxtQuery is cleared

Clear `TxtQuery` after getting selection

---

Pinpoint.Plugin.ProcessManager/Pinpoint.Plugin.ProcessManager.csproj
Pinpoint.Plugin.ProcessManager/ProcessManagerPlugin.cs
Pinpoint.Win/Pinpoint.Win.csproj
Pinpoint.Win/View/MainWindow.xaml.cs
Pinpoint.sln

Process manager plugin

---

Pinpoint.Core/Pinpoint.Core.csproj
Pinpoint.Plugin.AppSearch/Pinpoint.Plugin.AppSearch.csproj
Pinpoint.Plugin.Bangs/Pinpoint.Plugin.Bangs.csproj
Pinpoint.Plugin.Bookmarks/Pinpoint.Plugin.Bookmarks.csproj
Pinpoint.Plugin.Calculator/Pinpoint.Plugin.Calculator.csproj
Pinpoint.Plugin.ClipboardManager/Pinpoint.Plugin.ClipboardManager.csproj
Pinpoint.Plugin.ColorConverter/Pinpoint.Plugin.ColorConverter.csproj
Pinpoint.Plugin.CommandLine/Pinpoint.Plugin.CommandLine.csproj
Pinpoint.Plugin.ControlPanel/Pinpoint.Plugin.ControlPanel.csproj
Pinpoint.Plugin.Currency/Pinpoint.Plugin.Currency.csproj
Pinpoint.Plugin.Dictionary/Pinpoint.Plugin.Dictionary.csproj
Pinpoint.Plugin.EncodeDecode/Pinpoint.Plugin.EncodeDecode.csproj
Pinpoint.Plugin.Everything/Pinpoint.Plugin.Everything.csproj
Pinpoint.Plugin.Finance/Pinpoint.Plugin.Finance.csproj
Pinpoint.Plugin.HackerNews/Pinpoint.Plugin.HackerNews.csproj
Pinpoint.Plugin.MetricConverter/Pinpoint.Plugin.MetricConverter.csproj
Pinpoint.Plugin.Notes/Pinpoint.Plugin.Notes.csproj
Pinpoint.Plugin.OperatingSystem/Pinpoint.Plugin.OperatingSystem.csproj
Pinpoint.Plugin.PasswordGenerator/Pinpoint.Plugin.PasswordGenerator.csproj
Pinpoint.Plugin.ProcessManager/Pinpoint.Plugin.ProcessManager.csproj
Pinpoint.Plugin.Reddit/Pinpoint.Plugin.Reddit.csproj
Pinpoint.Plugin.Spotify/Pinpoint.Plugin.Spotify.csproj
Pinpoint.Plugin.UrlLauncher/Pinpoint.Plugin.UrlLauncher.csproj
Pinpoint.Plugin.Weather/Pinpoint.Plugin.Weather.csproj
Pinpoint.Win/Pinpoint.Win.csproj

Upgrade to .NET 5

---

Pinpoint.Plugin.Spotify/Client/SpotifyClient.cs

If play goes wrong because of no current session, query for available devices and just play on the first one.
Closes #113

Query for available devices if play fails

---

Pinpoint.Core/Clipboard/ClipboardHelper.cs
Pinpoint.Core/Clipboard/ClipboardHistory.cs
Pinpoint.Core/Clipboard/TextClipboardEntry.cs
Pinpoint.Core/NativeProvider.cs
Pinpoint.Plugin.AppSearch/AppResult.cs
Pinpoint.Plugin.ClipboardManager/ClipboardResult.cs
Pinpoint.Win/ViewModels/MainViewModel.cs
Pinpoint.Win/Views/MainWindow.xaml
Pinpoint.Win/Views/MainWindow.xaml.cs

Don't append duplicate content to clipboard history

---

Pinpoint.Plugin.AppSearch/AppResult.cs
Pinpoint.Plugin.AppSearch/AppSearchPlugin.cs
Pinpoint.Plugin.Spotify/Client/SpotifyClient.cs
Pinpoint.Plugin.Spotify/SpotifyPlugin.cs
Pinpoint.Plugin.Spotify/SpotifySearchResult.cs

Initiate playback before starting specific song

---

Pinpoint.Plugin.AppSearch/AppSearchPlugin.cs
Pinpoint.Plugin.AppSearch/StandardAppProvider.cs

And I also added the _Desktop_ as a source for apps.

Exclude app extensions from their name

---

Pinpoint.Win/Views/MainWindow.xaml.cs
Pinpoint.Win/Views/SettingsWindow.xaml

Adds a version check to window loaded method
A prompt is shown if current version does not match version of most recent GitHub release

Check for newer app version on boot

---

Pinpoint.Win/Views/SettingsWindow.xaml
Pinpoint.Win/Views/SettingsWindow.xaml.cs

Adds checkbox which adds/removes the executable to the registry database, causing the application to run at Windows startup.
Closes #151

Added option to start pinpoint on windows boot.

---

Pinpoint.Plugin.AppSearch/AppSearchPlugin.cs

Still build trie from UWP apps since they are slow to fetch

Fetch apps on-the-fly to support installations made after launch of Pinpoint

---

Pinpoint.Win/Views/MainWindow.xaml.cs

Hide window on ESC presses no matter what

---

Pinpoint.Plugin.Bookmarks/BraveBookmarkFileLocator.cs
Pinpoint.Plugin.Bookmarks/ChromeBookmarkExtractor.cs
Pinpoint.Plugin.Bookmarks/FirefoxBookmarkExtractor.cs
Pinpoint.Plugin.Bookmarks/IBookmarkFileLocator.cs

Adds support for different Firefox variants
Closes #155

Support fetching bookmarks for multiple variants of Firefox

---

Pinpoint.Win/ViewModels/MainViewModel.cs

Suppress clipboard hook exception on Windows boot

---

Pinpoint.Plugin.AppSearch/StandardAppProvider.cs

Include .appref-ms app references in app search results

---

Pinpoint.Core/Clipboard/ClipboardHelper.cs
Pinpoint.Core/Query.cs
Pinpoint.Plugin.ClipboardUploader/ClipboardUploaderPlugin.cs
Pinpoint.Plugin.Emoji/EmojiPlugin.cs
Pinpoint.Plugin.Emoji/Pinpoint.Plugin.Emoji.csproj
Pinpoint.Plugin.PasswordGenerator/PasswordResult.cs
Pinpoint.Plugin.UrlLauncher/UrlLauncherPlugin.cs
Pinpoint.Win/Pinpoint.Win.csproj
Pinpoint.Win/Views/MainWindow.xaml.cs
Pinpoint.Win/Views/SettingsWindow.xaml
Pinpoint.sln

Implement emoji plugin

---

Pinpoint.Win/Views/SettingsWindow.xaml
Pinpoint.Win/Views/SettingsWindow.xaml.cs

- Change checkbox to button
- Show feedback

Show feedback when toggling launch on startup

---

Pinpoint.Plugin.AppSearch/AppSearchPlugin.cs
Pinpoint.Plugin.AppSearch/DirectoryAppProvider.cs
Pinpoint.Plugin.AppSearch/PathAppProvider.cs
Pinpoint.Plugin.AppSearch/StandardAppProvider.cs

Provide apps from $PATH

---

Pinpoint.Plugin.AppSearch/AppSearchPlugin.cs

For example:
```
DataGrip -> [data,grip]
```

Generate better aliases for apps with CamelCase naming

---

Pinpoint.Win/ViewModels/ObservableUniqueCollection.cs
Pinpoint.Win/Views/MainWindow.xaml.cs

- Fix key up navigation
- Support searching in clipboard results
- Better context switching

Fix clipboard manager quirks

---

Pinpoint.Core/AbstractPlugin.cs

Fix crash on startup if Pinpoint home directory doesn't exist

---

Pinpoint.Plugin.Windower/Pinpoint.Plugin.Windower.csproj
Pinpoint.Plugin.Windower/WindowManager.cs
Pinpoint.Plugin.Windower/WindowModel.cs
Pinpoint.Plugin.Windower/WindowResult.cs
Pinpoint.Plugin.Windower/WindowerPlugin.cs
Pinpoint.Win/Pinpoint.Win.csproj
Pinpoint.Win/Views/MainWindow.xaml.cs
Pinpoint.sln
README.md

- Initial windower plugin
- Implement essential functionality
- Don't cast window results
- Set window result subtitle to process name
- Add example
- Consistency

Implement window switcher plugin

---

Pinpoint.Plugin.GuidGenerator/GuidGeneratorPlugin.cs
Pinpoint.Plugin.GuidGenerator/Pinpoint.Plugin.GuidGenerator.csproj
Pinpoint.Win/Pinpoint.Win.csproj
Pinpoint.Win/Views/MainWindow.xaml.cs
Pinpoint.sln

Simple plugin to generate GUIDs/UUIDs. Results are copyable and displayed both with and without hyphens.

Adds a plugin for generating guids/uuids.

---

Pinpoint.Plugin/AbstractPlugin.cs

Ensure plugin settings directory exists prior to saving
